
development:
  adapter: mysql
  database: bigbrainloris
  host: localhost
  username: bigbrainloris
  password: ZombieFoodNetwork

production:
  adapter: mysql
  database: bigbrainloris
  host: localhost
  username: bigbrainloris
  password: ZombieFoodNetwork

